<div class="panel panel-default">
    <div class="panel-body">
        <form class="form" method="post" enctype="multipart/form-data">
            <div class="pull-left">
                <div class="btn-group">
                    <a href="<?php echo $this->linkToRoute('admin-videos');?>" class="btn btn-success"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
                </div>

                <div class="btn-group">
                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> <?php echo $this->translate('Save');?></button>
                </div>
            </div>
            <div class="clearfix"></div>
            <hr>
<?php
if (isset($this->result)) {
    $status = (isset($this->result['errors']) ? 'danger' : 'success');
    echo Fennec\Library\Alerts::Create($status, $this->result['result']);
}
?>

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12">
                        <label for="url"><?php echo $this->translate('Enter video URL');?></label>
                        <input type="url" name="url" id="url" class="form-control" required value="<?php echo (isset($this->url) ? $this->url : null);?>" maxlength="255">
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-12">
                        <label for="title"><?php echo $this->translate('Video title');?></label>
                        <input type="text" name="title" id="title" class="form-control" required value="<?php echo (isset($this->title) ? $this->title : null);?>" maxlength="255">
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-xs-12">
                        <label for="description"><?php echo $this->translate('Description');?></label>
                        <textarea class="form-control" name="description" id="description"><?php echo (isset($this->description) ? $this->description: null);?></textarea>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> <?php echo $this->translate('Save');?></button>
            </div>
        </form>
    </div>
</div>
